scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9112']

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9112']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-exporter:8083']
